export const GET_ALL_PLANTDATA_REQUEST = "GET_ALL_PLANTDATA_REQUEST";
export const GET_ALL_PLANTDATA_SUCCESS =  "GET_ALL_PLANTDATA_SUCCESS";
export const GET_ALL_PLANTDATA_FAILURE = "GET_ALL_PLANTDATA_FAILURE";